server:
  port: 8082

spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/comittedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres
      mode: always
  # JPA/Hibernate Configuration
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # none/validate/update/create/create-drop/use 'validate' in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

# ---------------------------------------------------
# --- SpringDoc (Swagger) OpenAPI 3 Configuration ---
# ---------------------------------------------------
springdoc:
  # Custom path for the Swagger UI
  swagger-ui:
    path: /swagger-ui.html
  # Path for the API documentation in JSON format
  api-docs:
    path: /api-docs
  # General API information
  info:
    title: "Comitte Application API"
    description: "API documentation for the Comitte application."
    version: "v1.0.0"
    contact:
      name: "API Support Team"
      email: "support@example.com"

logging:
  level:
    com.example.comitte: DEBUG # Sets the log level to DEBUG for your application's packages
    org.springframework.web: DEBUG # Sets the log level to INFO for Spring Web classes
    org.hibernate: ERROR # Sets the log level to ERROR for Hibernate (JPA)
